// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice_SQL.Models;

namespace Practice_SQL.Migrations
{
    [DbContext(typeof(CarsCodeFirstContext))]
    [Migration("20200917173257_SeedDataRNG1")]
    partial class SeedDataRNG1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Practice_SQL.Models.CodeFirstCar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnName("colour")
                        .HasColumnType("varchar(10)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnName("manufacturer")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("model")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("Odometer")
                        .HasColumnName("odometer")
                        .HasColumnType("int(10)");

                    b.Property<string>("TrimLevel")
                        .IsRequired()
                        .HasColumnName("trim_level")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.ToTable("code_first_car");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            Odometer = 208070,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 2,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Durango",
                            Odometer = 60081,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 3,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Fusion",
                            Odometer = 72040,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 4,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            Odometer = 188314,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 5,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 189582,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 6,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Fusion",
                            Odometer = 118331,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 7,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Durango",
                            Odometer = 153647,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 8,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Corvette",
                            Odometer = 227813,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 9,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            Odometer = 267733,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 10,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Corvette",
                            Odometer = 113748,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 11,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Durango",
                            Odometer = 240751,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 12,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Fusion",
                            Odometer = 224845,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 13,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 75008,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 14,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 118603,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 15,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 123966,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 16,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Fusion",
                            Odometer = 176894,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 17,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 178276,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 18,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Corvette",
                            Odometer = 265749,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 19,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Fusion",
                            Odometer = 69924,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 20,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Corvette",
                            Odometer = 274278,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 21,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Fusion",
                            Odometer = 6983,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 22,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Corvette",
                            Odometer = 248904,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 23,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 96046,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 24,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Fusion",
                            Odometer = 23396,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 25,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Fusion",
                            Odometer = 18930,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 26,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 161709,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 27,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Fusion",
                            Odometer = 260370,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 28,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Fusion",
                            Odometer = 279522,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 29,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Fusion",
                            Odometer = 278786,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 30,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Fusion",
                            Odometer = 123571,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 31,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 3042,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 32,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Fusion",
                            Odometer = 59028,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 33,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            Odometer = 122879,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 34,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Fusion",
                            Odometer = 136405,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 35,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 245756,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 36,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 255554,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 37,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Fusion",
                            Odometer = 110586,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 38,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Durango",
                            Odometer = 279097,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 39,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Fusion",
                            Odometer = 115867,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 40,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 82972,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 41,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 2740,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 42,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            Odometer = 99880,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 43,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 161763,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 44,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 95119,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 45,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Corvette",
                            Odometer = 207669,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 46,
                            Colour = "Black",
                            Manufacturer = "Ford",
                            Model = "Corvette",
                            Odometer = 198777,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 47,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Durango",
                            Odometer = 23173,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 48,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Fusion",
                            Odometer = 135522,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 49,
                            Colour = "Black",
                            Manufacturer = "Chevrolet",
                            Model = "Durango",
                            Odometer = 163715,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 50,
                            Colour = "Black",
                            Manufacturer = "Dodge",
                            Model = "Corvette",
                            Odometer = 246124,
                            TrimLevel = "R/T"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
