// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice_SQL.Models;

namespace Practice_SQL.Migrations
{
    [DbContext(typeof(CarsCodeFirstContext))]
    [Migration("20200917203951_ForeignKey")]
    partial class ForeignKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Practice_SQL.Models.CodeFirstCar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnName("colour")
                        .HasColumnType("varchar(10)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("ManufacturerID")
                        .HasColumnName("manufacturer_id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnName("model")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("Odometer")
                        .HasColumnName("odometer")
                        .HasColumnType("int(10)");

                    b.Property<string>("TrimLevel")
                        .IsRequired()
                        .HasColumnName("trim_level")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.HasKey("ID");

                    b.HasIndex("ManufacturerID")
                        .HasName("FK_CodeFirstCar_Manufacturer");

                    b.ToTable("code_first_car");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 236538,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 2,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 294356,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 3,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 154746,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 4,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 187814,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 5,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 200710,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 6,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 49376,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 7,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 13739,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 8,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 134788,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 9,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 19503,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 10,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 221560,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 11,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 222762,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 12,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 214960,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 13,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 222791,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 14,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 38943,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 15,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 60264,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 16,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 74346,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 17,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 1394,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 18,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 134184,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 19,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 23136,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 20,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 115904,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 21,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 280638,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 22,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 117764,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 23,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 163918,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 24,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 124556,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 25,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 199479,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 26,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 6075,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 27,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 248707,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 28,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 212064,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 29,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 37897,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 30,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 253386,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 31,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 119447,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 32,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 102908,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 33,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 169264,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 34,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 211719,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 35,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 43215,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 36,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 24454,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 37,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 230320,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 38,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 182085,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 39,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 287470,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 40,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 164120,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 41,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 136620,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 42,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 120921,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 43,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 174285,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 44,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 202990,
                            TrimLevel = "Awesome"
                        },
                        new
                        {
                            ID = 45,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 228620,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 46,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 54504,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 47,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Durango",
                            Odometer = 58346,
                            TrimLevel = "High Country"
                        },
                        new
                        {
                            ID = 48,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 44481,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 49,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Corvette",
                            Odometer = 274594,
                            TrimLevel = "R/T"
                        },
                        new
                        {
                            ID = 50,
                            Colour = "Black",
                            ManufacturerID = 1,
                            Model = "Fusion",
                            Odometer = 25762,
                            TrimLevel = "Awesome"
                        });
                });

            modelBuilder.Entity("Practice_SQL.Models.Manufacturer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int?>("YearFounded")
                        .HasColumnName("year_founded")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.ToTable("manufacturer");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Chevrolet",
                            YearFounded = 1911
                        },
                        new
                        {
                            ID = 2,
                            Name = "Ford",
                            YearFounded = 1903
                        },
                        new
                        {
                            ID = 3,
                            Name = "Tesla"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Dodge"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Toyota",
                            YearFounded = 1937
                        },
                        new
                        {
                            ID = 6,
                            Name = "Honda",
                            YearFounded = 1946
                        },
                        new
                        {
                            ID = 7,
                            Name = "Mitsubishi"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Nissan"
                        });
                });

            modelBuilder.Entity("Practice_SQL.Models.CodeFirstCar", b =>
                {
                    b.HasOne("Practice_SQL.Models.Manufacturer", "ManufacturerRed")
                        .WithMany("Cars")
                        .HasForeignKey("ManufacturerID")
                        .HasConstraintName("FK_CodeFirstCar_Manufacturer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
